export {
  __resetDirtyTrackerForTests,
  type AttachOptions,
  attachDirtyTracker,
  type DirtyEntry,
  type DirtyTransitionEvent,
  type DirtyTransitionListener,
  detachDirtyTracker,
  getDirtyEntry,
  isDirty,
  type MarkSavedOptions,
  markSaved,
  subscribeAllDirtyTransitions,
  subscribeAllSaved,
  subscribeFileDirty,
  updateLoadedMetadata,
} from "./dirty-tracker";
export { ensureModelWithContent } from "./ensure-model";
export { relPathForInput, workspaceRootForInput } from "./file-loader";
export {
  acquireModel,
  cacheUriFor,
  cacheUriToFilePath,
  clearDiskDiverged,
  type EntryMetadata,
  forceDisposeExternalsForWorkspace,
  getEntryMetadata,
  getModelSnapshot,
  getResolvedModel,
  initializeModelCache,
  parseCacheUri,
  type ReleasedModelInfo,
  reloadModelFromDisk,
  type ResolvedModelView,
  releaseModel,
  type SharedModelPhase,
  type SharedModelState,
  subscribeModel,
  subscribeOnRelease,
  toFileErrorCode,
} from "./cache";
export { useSharedModel } from "./use-shared-model";
