import { createHash } from "node:crypto";
import { chmod, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import type { WorkspaceId } from "../../../shared/src/contracts/workspace";

export const OPENCODE_HOST = "127.0.0.1";
export const OPENCODE_PORT_BASE = 43_000;
export const OPENCODE_PORT_SPAN = 2_000;
export const OPENCODE_CONFIG_CONTENT_ENV = "OPENCODE_CONFIG_CONTENT";
export const NEXUS_OPENCODE_HOST_ENV = "NEXUS_OPENCODE_HOST";
export const NEXUS_OPENCODE_PORT_ENV = "NEXUS_OPENCODE_PORT";
export const NEXUS_OPENCODE_SHIM_DIR_ENV = "NEXUS_OPENCODE_SHIM_DIR";
export const NEXUS_OPENCODE_ORIGINAL_PATH_ENV = "NEXUS_OPENCODE_ORIGINAL_PATH";
export const NEXUS_OPENCODE_ZDOTDIR_ENV = "NEXUS_OPENCODE_ZDOTDIR";
export const NEXUS_OPENCODE_ORIGINAL_ZDOTDIR_ENV = "NEXUS_OPENCODE_ORIGINAL_ZDOTDIR";

const ZSH_STARTUP_FILES = [".zshenv", ".zprofile", ".zshrc", ".zlogin"] as const;

type ZshStartupFile = (typeof ZSH_STARTUP_FILES)[number];

export interface OpenCodeTerminalEnvOptions {
  readonly shimDir?: string;
  readonly basePath?: string;
  readonly zshDotDir?: string;
  readonly baseZdotDir?: string;
}

export interface OpenCodeShimOptions {
  readonly dataDir: string;
  readonly workspaceId: WorkspaceId;
}

export interface OpenCodeWorkspaceShimPaths {
  readonly executableShimDir: string;
  readonly zshDotDir: string;
}

export function resolveOpenCodePort(workspaceId: WorkspaceId): number {
  const digest = createHash("sha256").update(workspaceId, "utf8").digest("hex");
  const value = Number.parseInt(digest.slice(0, 8), 16);
  return OPENCODE_PORT_BASE + (value % OPENCODE_PORT_SPAN);
}

export function buildOpenCodeConfigContent(workspaceId: WorkspaceId): string {
  return JSON.stringify({
    server: {
      hostname: OPENCODE_HOST,
      port: resolveOpenCodePort(workspaceId),
    },
  });
}

export function buildOpenCodeTerminalEnvOverrides(
  workspaceId: WorkspaceId,
  options: OpenCodeTerminalEnvOptions = {},
): Record<string, string> {
  const env: Record<string, string> = {
    [OPENCODE_CONFIG_CONTENT_ENV]: buildOpenCodeConfigContent(workspaceId),
    [NEXUS_OPENCODE_HOST_ENV]: OPENCODE_HOST,
    [NEXUS_OPENCODE_PORT_ENV]: String(resolveOpenCodePort(workspaceId)),
  };

  if (options.shimDir) {
    env[NEXUS_OPENCODE_SHIM_DIR_ENV] = options.shimDir;
    env[NEXUS_OPENCODE_ORIGINAL_PATH_ENV] = options.basePath ?? "";
    env.PATH = prependPath(options.shimDir, options.basePath ?? "");
  }

  if (options.zshDotDir) {
    env.ZDOTDIR = options.zshDotDir;
    env[NEXUS_OPENCODE_ZDOTDIR_ENV] = options.zshDotDir;
    env[NEXUS_OPENCODE_ORIGINAL_ZDOTDIR_ENV] = options.baseZdotDir ?? "";
  }

  return env;
}

export async function ensureOpenCodeWorkspaceShim(
  options: OpenCodeShimOptions,
): Promise<string> {
  const paths = await ensureOpenCodeWorkspaceShims(options);
  return paths.executableShimDir;
}

export async function ensureOpenCodeWorkspaceShims(
  options: OpenCodeShimOptions,
): Promise<OpenCodeWorkspaceShimPaths> {
  const executableShimDir = openCodeShimDir(options.dataDir, options.workspaceId);
  await mkdir(executableShimDir, { recursive: true });
  const shimPath = path.join(executableShimDir, "opencode");
  await writeFile(shimPath, buildOpenCodeShimScript(), "utf8");
  await chmod(shimPath, 0o755);

  const zshDotDir = openCodeZshDotDir(options.dataDir, options.workspaceId);
  await mkdir(zshDotDir, { recursive: true });
  await Promise.all(
    ZSH_STARTUP_FILES.map((startupFile) =>
      writeFile(
        path.join(zshDotDir, startupFile),
        buildOpenCodeZshStartupScript(startupFile),
        "utf8",
      ),
    ),
  );

  return { executableShimDir, zshDotDir };
}

export function openCodeShimDir(dataDir: string, workspaceId: WorkspaceId): string {
  return path.join(dataDir, "opencode-shims", workspaceId, "bin");
}

export function openCodeZshDotDir(dataDir: string, workspaceId: WorkspaceId): string {
  return path.join(dataDir, "opencode-shims", workspaceId, "zsh");
}

export function buildOpenCodeShimScript(): string {
  return `#!/bin/sh
set -eu

host=\${${NEXUS_OPENCODE_HOST_ENV}:-${OPENCODE_HOST}}
port=\${${NEXUS_OPENCODE_PORT_ENV}:?Nexus OpenCode shim missing ${NEXUS_OPENCODE_PORT_ENV}}
original_path=\${${NEXUS_OPENCODE_ORIGINAL_PATH_ENV}:-}

if [ -z "$original_path" ]; then
  echo "Nexus OpenCode shim: ${NEXUS_OPENCODE_ORIGINAL_PATH_ENV} is empty; cannot locate real opencode." >&2
  exit 127
fi

old_ifs=$IFS
IFS=:
for dir in $original_path; do
  IFS=$old_ifs
  [ -n "$dir" ] || dir=.
  candidate="$dir/opencode"
  if [ -x "$candidate" ]; then
    exec "$candidate" --hostname "$host" --port "$port" "$@"
  fi
  IFS=:
done
IFS=$old_ifs

echo "Nexus OpenCode shim: real opencode binary not found on PATH." >&2
exit 127
`;
}

export function buildOpenCodeZshStartupScript(startupFile: ZshStartupFile): string {
  return `# Generated by Nexus. Do not edit.
# Keeps the workspace OpenCode shim first even when user zsh startup files rebuild PATH.
_nexus_opencode_source_user_zdot() {
  local _nexus_startup_file="$1"
  local _nexus_wrapper_zdotdir="\${${NEXUS_OPENCODE_ZDOTDIR_ENV}:-\${ZDOTDIR:-}}"
  local _nexus_user_zdotdir="\${${NEXUS_OPENCODE_ORIGINAL_ZDOTDIR_ENV}:-\${HOME:-}}"

  if [ -z "$_nexus_user_zdotdir" ]; then
    return
  fi
  if [ -n "$_nexus_wrapper_zdotdir" ] && [ "$_nexus_user_zdotdir" = "$_nexus_wrapper_zdotdir" ]; then
    return
  fi
  if [ ! -r "$_nexus_user_zdotdir/$_nexus_startup_file" ]; then
    return
  fi

  export ZDOTDIR="$_nexus_user_zdotdir"
  source "$_nexus_user_zdotdir/$_nexus_startup_file"
  export ${NEXUS_OPENCODE_ORIGINAL_ZDOTDIR_ENV}="\${ZDOTDIR:-$_nexus_user_zdotdir}"
  if [ -n "$_nexus_wrapper_zdotdir" ]; then
    export ZDOTDIR="$_nexus_wrapper_zdotdir"
  else
    unset ZDOTDIR
  fi
}

_nexus_opencode_prepend_shim() {
  local _nexus_shim_dir="\${${NEXUS_OPENCODE_SHIM_DIR_ENV}:-}"
  if [ -z "$_nexus_shim_dir" ]; then
    return
  fi

  path=("$_nexus_shim_dir" "\${path[@]:#$_nexus_shim_dir}")
  export PATH
  rehash 2>/dev/null || true
}

_nexus_opencode_source_user_zdot "${startupFile}"
_nexus_opencode_prepend_shim
unset -f _nexus_opencode_source_user_zdot _nexus_opencode_prepend_shim
`;
}

function prependPath(prefix: string, basePath: string): string {
  return basePath.trim().length > 0 ? `${prefix}:${basePath}` : prefix;
}
